# Generated by Django 5.1.1 on 2024-10-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ex04", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="id",
        ),
        migrations.AddField(
            model_name="movie",
            name="opening_crawl",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="movie",
            name="episode_nb",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="movie",
            name="producer",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
