# Generated by Django 5.1.1 on 2024-10-03 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Planets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("climate", models.CharField(max_length=100)),
                ("diameter", models.FloatField()),
                ("orbital_period", models.IntegerField()),
                ("population", models.BigIntegerField(blank=True, null=True)),
                ("rotation_period", models.IntegerField()),
                ("surface_water", models.FloatField()),
                ("terrain", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("release_date", models.DateField()),
                ("characters", models.ManyToManyField(to="ex10.people")),
            ],
        ),
        migrations.AddField(
            model_name="people",
            name="homeworld",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ex10.planets"
            ),
        ),
    ]
